customhost = "employee.cqqfjwe1w1ma.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = benedictteashangzhe-employee"
customregion = "us-east-1"
